### ISSUE TITLE
Todo 2021

### ISSUE THREAD

**Issue by Karsens** [Code-From-Anywhere/mastercrimez4#12]
# 1 januari: territoriums
- [x] done

# 15 januari: OC
- [x] verander releasedate overal
- [x] verander supermessage
- [x] copy from streetace
- [x] voeg vertalingen toe

# Prijzen (1 februari)
- [x] verander frontend/backend releasedate naar 1 feb
- [x] verander datum superbericht
- [x] prize model
- [x] get prizes endpoint, ook huidige statistieken includen
- [x] statistieken per prijs frontend
- [x] automatische prijzen uitbetalen aan de hand van model en cron

# Anti-bot / subs / admin stuff (15 februari)
- [x] see if I can create my own captcha with nodeJS and react-native
- [x] on web, send mousemovements(and timestamps) and menuclicks to server every minute
- [x] on app, send menu click positions(and timestamps) to server every minute
- [x] save actions in an actionlog for all actions
- [x] plot mouse movements/pages/menu click positiions against actions on timescale in admin panel
- [x] team page in info
- [x] team: berichten checken, bans uitdelen, bans/verifies uitdelen voor subs, accounts resetten
- [x] save ip address on me call, maak users overzicht ordered by ip en online < 24 hours. 
- [x] maak het mogelijk accounts te resetten bij subs/botten en ook ip's te bannen
- [x] maak het mogelijk accounts te unverifyen qua sms als verdacht word van botten
- [x] maak admin action log
- [x] geef alle mods toegang tot acc ban/reset/unverify en ip overzicht en actions overzicht
- [x] rapporteren berichten + balk

# Streetraces (1 maart)
- [x] add streetraces (with added pricemoney) in CRON, daily and weekly - add push notificatie bij de weekly race

# Beroepen (15 maart)
- [x] add backend to choose Profession
- [x] add frontend to choose profession
- [x] add link to chooseprofession on status if available
- [x] add profession image to profile after release
- [x] add advantages to crimes etc.

# Paasdagen (1 april)
- [x] Eieren kunnen vinden met prijzen erin bij misdaden, auto stelen, hoeren, junkies, wiet
- [x] Maak ook 'cadeaus' vinden bji kerst en halloween bij deze features

# 15 april: Territoriums
- [x] Eerst voor 3 steden toevoegen, elke week een stad erbij
- [x] verander release date

# 1 mei: Gang Missies
- [x] done

# 15 april: Werken
- [x] verander release date en supermessage
- [x] maak cron dat werken voltooid is elke minuut
- [x] maak backend onbereikbaar indien niet gereleased
- [x] kopieer werken script voor schoentje zetten sinterklaas

# 1 juni: Detectives
- [x] done

# 15 Juni: Winkelroof met je vrienden: 
- [x] wapenexpert, vluchtwagen, (en misschien nog meer). copy from streetrace

#  1 juli: Casino uitgebreider: lotto
- [x] done

# 15 juli: Gevorderde misdaden

# Politie (1 augustus)
- [x] verander releasedate en superbericht
- [x] Attacks moeten in gangchat komen zodat het duidelijk is dat attacks worden uitgevoerd
- [x] endpoint voor gangs isPolice dat members en bullets uitpoept
- [x] dit op frontend tonen
- [x] Automatisch kogels op de gangbank zetten per dag als kogels <X

# 15 augustus: gang bullet factory
- [x] add proper logging to the gang chat

# 1 september: territorium

# 15 september: aandelen beurs
- [ ] elke week een nieuwe beursgang

# 1 oktober: Nog een casino spel

# 15 oktober: Halloween
- [x] Cadeaus kunnen vinden

# 1 november: Wedkantoor: 
- [ ] moeilijk te automatiseren, maar d.m.v. een api kan het. 

# Sinterklaas: (15 november)
- [x] Schoen kunnen zetten, dikke prijzen in je schoen
- [x] Speciale auto kunnen stelen (Sinterwagon)

# 1 december:Aanslagenlijst

# Kerst: 15 december
- [x] Kerst: Cadeau's kunnen vinden

# 2022+

# Happy hour (1 januari)
- [x] verplaats supermessage
- [x] verander releaseDate backend
- [x] Happy hour 19-20 double + push notificatie
- [x] Happy day sunday double + push notificatie

# 15 januari: Missies, prestige
- [x] verander supermessage
- [ ] denk na over wat ik wil met missies. wat voor type missies zijn leuk?
 
# 1 februari: Poker
- [ ] ECHT POKER MAKEN

Elke 2 weken een nieuwe feature, dus 25 nieuwe features bedenken die er in kunnen komen
